name: Code Quality (Lint & Format)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      # --frozen-lockfile garante que ele não tente atualizar o yarn.lock no CI
      - name: Instalar dependências
        run: yarn install --frozen-lockfile

      - name: Rodar Prettier
        run: yarn format --check

      - name: Rodar ESLint
        run: yarn lint